export default {
	ordinalNum:{
		1: '1st',
		2: '2nd',
		3: '3rd',
		4: '4th',
		5: '5th',
	},
	enlRetFormat:{
		"I": "Inventory",
		"E": "Eligible",
		"K": "Keep",
		"RR": "Reenlistment Ratio",
		"KR": "Keep Ratio"
	},
	catFormat:{
		"1":"1ST TERM",
		"2":"2ND TERM",
		"C":"CAREER"
	},
	majFormat : {
		" ":"UNKNOWN",
		"02":"AFIA",
		"03":"AFOTEC",
		"04":"AFCOMM AG",
		"05":"AFIAA",
		"06":"AFAA",
		"07":"AFOSI",
		"08":"HQ AFSFC",
		"09":"AFPC",
		"0B":"US AFA",
		"0D":"USAFE",
		"0J":"AETC",
		"0M":"AFR",
		"0N":"HQ USAF",
		"0R":"PACAF",
		"0V":"AFSOC",
		"11":"AF MPA",
		"12":"AF PA AGY",
		"13":"HQAF SUP AGY",
		"14":"INSTAL CONTR",
		"15":"CIV ENG CNTR",
		"16":"MORT AFRS OP",
		"17":"INSTAL MSM S",
		"18":"DEF HLTH AGY",
		"1A":"AF C2ISRC",
		"1B":"AF MAA",
		"1C":"ACC",
		"1G":"HQ AFLMA",
		"1K":"AF CYBER CMD",
		"1L":"AMC",
		"1M":"AFMC",
		"1P":"AF RL PR AGY",
		"1Q":"HQ AFFSA",
		"1R":"AFRICA CMD",
		"1S":"AFSPC",
		"1W":"AFCESA",
		"1Y":"AFCCT",
		"20":"AF AGY MOD/S",
		"21":"AF NWA",
		"23":"AFELM OSIA(H",
		"24":"HQ USAF DSE",
		"25":"AFWSE",
		"26":"AFBMDO",
		"27":"AFAM-S",
		"28":"AF COM-INFO",
		"29":"AF NAT SEC E",
		"2A":"AFCAA",
		"2B":"AFOC",
		"2D":"AFPOA",
		"2E":"AFLSA",
		"2F":"HQ AFMSA",
		"2G":"AFNA",
		"2H":"AFOG",
		"2I":"ANGRC",
		"2K":"AF HRA",
		"2L":"AF TAC",
		"2M":"AF RBO",
		"2N":"AF CSA",
		"2Q":"HQ AFWA",
		"2R":"AFPEO",
		"2S":"AFELM NORAD",
		"2T":"AF SAFE CTR",
		"2U":"AF SVR AGY",
		"2V":"AFBDA",
		"2W":"11TH WG",
		"2X":"AFREA",
		"2Y":"AFPCA",
		"2Z":"HQ AFMOA",
		"30":"AFELM DISA",
		"31":"AFELM DFAS",
		"32":"ANG - FTS",
		"33":"AFELM DLA",
		"34":"ANG - MOB",
		"35":"AFELM DIA",
		"36":"AFELM NIMA",
		"37":"DEF TR AGY",
		"38":"AFELM JCS",
		"39":"AFELM OSD FA",
		"3A":"CMA",
		"3B":"DEF MEDIA AC",
		"3C":"USCENTCOM",
		"3D":"USSOCOM",
		"3G":"AFELM NATO",
		"3I":"RES. CM",
		"3K":"USEUCOM",
		"3L":"CTR AF HIST",
		"3M":"USSOUTHCOM",
		"3N":"USJFCOM",
		"3O":"USPACOM",
		"3P":"CNTRINTEL FA",
		"3Q":"USSTRATCOM",
		"3S":"USSPACECOM",
		"3T":"USTRANSCOM",
		"3V":"AFELM (OTH)",
		"3W":"AFCEE",
		"3Y":"AF FMA",
		"3Z":"JSSEREA",
		"40":"NAT AIR INTL",
		"41":"AFELM NGA",
		"4C":"AFELM CYBER CM",
		"4D":"AFELM NORTHCOM",
		"4L":"FUTURE FINAN",
		"4V":"NON-DOD/OTHE",
		"4W":"AF DIST WASH",
		"5J":"AF FSC",
		"5K":"AF PETRO AGY",
		"77":"ARM",
		"87":"DEC",
		"99":"USARC",
		"GS":"GLOBAL STRKE",
		"YY":"N/A"
	},
	mpfFormat : {
		"**":"UNKNOWN",
		"AM":"ALTUS AFB OK",
		"AT":"ANDERSEN AFB GU",
		"AU":"JB ANDREWS AFB MD",
		"AY":"AVIANO ABS IT",
		"BB":"BARKSDALE AFB LA",
		"BD":"BEALE AFB CA",
		"BP":"BOLLING AFB DC",
		"BU":"BUCKLEY AFB CO",
		"CD":"CANNON AFB NM",
		"CL":"JB CHARLESTON AFB SC",
		"CO":"COLUMBUS AFB MS",
		"DF":"DAVIS-MONTHAN AFB AZ",
		"DM":"DOVER AFB DE",
		"DW":"DYESS AFB TX",
		"EB":"EDWARDS AFB CA",
		"ED":"EGLIN AFB FL",
		"EE":"HURLBURT FIELD ABS FL",
		"EH":"EIELSON AFB AK",
		"EJ":"ELLSWORTH AFB SD",
		"EL":"JB ELMENDORF-RICH ABS AK",
		"EP":"PETERSON AFB CO",
		"FC":"FAIRCHILD AFB WA",
		"FD":"SCHRIEVER AFB CO",
		"FT":"FT GEORGE MEADE AIN MD",
		"FW":"F E WARREN AFB WY",
		"GF":"GOODFELLOW AFB AFD TX",
		"GM":"GRAND FORKS AFB ND",
		"HH":"PENTAGON ADM VA",
		"HL":"JB PRL HBR-HICKAM ABS HI",
		"HN":"FT SAM HOUSTON AIN TX",
		"HP":"HILL AFB UT",
		"HS":"HOLLOMAN AFB NM",
		"IN":"INCIRLIK AB ABS TR",
		"KB":"KADENA ABS JP",
		"KF":"KEESLER AFB MS",
		"KU":"KUNSAN ABS KR",
		"KV":"KIRTLAND AFB NM",
		"LA":"JBSA LACKLAND AFB TX",
		"LD":"LAKENHEATH ABS GB",
		"LE":"JB LANGLEY-EUSTIS ABS VA",
		"LJ":"LAUGHLIN AFB TX",
		"LK":"HANSCOM AFB MA",
		"LL":"LACKLAND AFB TX",
		"LP":"LITTLE ROCK AFB AR",
		"LU":"LOS ANGELES AFB CA",
		"LY":"LUKE AFB AZ",
		"MA":"MACDILL AFB FL",
		"MB":"MALMSTROM AFB MT",
		"MG":"MAXWELL AFB AL",
		"MH":"JBLM MCCHORD ABS WA",
		"MK":"MC CONNELL AFB KS",
		"ML":"MILDENHALL ABS GB",
		"MN":"JBMDL MCGUIRE AFB NJ",
		"MO":"MISAWA ABS JP",
		"MP":"MINOT AFB ND",
		"MT":"MOODY AFB GA",
		"MW":"MOUNTAIN HOME AFB ID",
		"NJ":"NELLIS AFB NV",
		"OD":"OFFUTT AFB NE",
		"OP":"OSAN AB ABS KR",
		"PE":"STUTTGART VAIHING CTY DE",
		"PF":"PATRICK AFB FL",
		"PV":"POPE AAF NC",
		"RF":"RAMSTEIN ABS DE",
		"RJ":"JBSA RANDOLPH AFB TX",
		"RX":"ROBINS AFB GA",
		"SF":"SCOTT AFB IL",
		"SM":"SEYMOUR JOHNSON AFB NC",
		"SP":"SHAW AFB SC",
		"SQ":"SHEPPARD AFB TX",
		"ST":"SPANGDAHLEM AB ABS DE",
		"TE":"TINKER AFB OK",
		"TP":"TRAVIS AFB CA",
		"TX":"TYNDALL AFB FL",
		"US":"USAF ACADEMY ACD CO",
		"VH":"VANCE AFB OK",
		"VQ":"VANDENBERG AFB CA",
		"WE":"WRIGHT PATTERSON AFB OH",
		"WG":"RKB-QUANTICO MGI VA",
		"WT":"WHITEMAN AFB MO",
		"YM":"YOKOTA ABS JP",
		"ZB":"LACKLAND AFB TX BMTS",
		"ZE":"USAF ACADEMY ACD CO CADET WING"
	},
	afscGroupFormat : {
		"1":"PENDING UPDATE",
		"2":"PENDING UPDATE",
		"3":"ABM",
		"4":"ACQUISITION",
		"5":"AEROSPACE MED",
		"6":"BIOMEDICAL",
		"7":"CHAP",
		"8":"DENTAL",
		"9":"HEALTH SVC",
		"10":"JAG",
		"11":"LOGISTICS",
		"12":"MEDICAL",
		"13":"MEDICAL CC",
		"14":"MSN SPT",
		"15":"NAV",
		"16":"NROPS",
		"17":"NURSE",
		"18":"OPERATIONS",
		"19":"OPERATIONS CC",
		"20":"PHYSICIAN",
		"21":"PILOT",
		"22":"PROFESSIONAL",
		"23":"REPORTING IDENTIFIERS",
		"24":"RI",
		"25":"RPA",
		"26":"SDI",
		"27":"SPECIAL DUTY IDENTIFIERS",
		"28":"SPECIAL INVESTIGATIONS",
		"29":"SUPPORT",
		"30":"SURGERY"
	},
	gradeFormat : {
        "01": "[01-02] LT",
        "02": "[01-02] LT",
        "03": "CPT",
        "04": "MAJ",
        "05": "LTC",
        "06": "COL",
        "31": "[31-33] AMN",
        "32": "[31-33] AMN",
        "33": "[31-33] AMN",
        "34": "SRA",
        "35": "SSG",
        "36": "TSG",
        "37": "MSG",
        "38": "SMS",
        "39": "CMS"
    }
    ,gradeOrder : {
	    "COL": 6,
	    "LTC": 5,
	    "MAJ": 4,
	    "CPT": 3,
	    "1LT": 2,
	    "2LT": 1,
	    "[01-02] LT": 0,
	    "CMS": 39,
	    "SMS": 38,
	    "MSG": 37,
	    "TSG": 36,
	    "SSG": 35,
	    "SRA": 34,
	    "A1C": 33,
	    "AMN": 32,
	    "AB": 31,
	    "[31-33] AMN": 30
	},
	zoneFormat : {
        "A": "APZ",
        "I": "IPZ",
        "B": "BPZ"
    },
    zoneOrder : {
        "APZ": 2,
        "IPZ": 1,
        "BPZ": 0

	},
	recommendFormat : {
        "D": "Definitely Promote",
        "L": "Not Required",
        "N": "Do Not Promote",
        "P": "Promote"
    },
    recommendOrder : {
        "Do Not Promote": 3,
        "Not Required": 2,
        "Promote": 1,
        "Definitely Promote": 0

	},
    compCatFormat: {
        "A": "Line",
        "C": "Chaplain",
        "D": "Dental",
        "J": "Judge Advocate",
        "M": "Medical",
        "N": "Nurse",
        "S": "Medical Service",
        "W": "Bio-medical Science"
    },
	pmeFormat : {
       "1": "Complete",
       "0": "Not Complete"
    },
    pmeOrder : {
        "Complete": 0,
        "Not Complete": 1

	},
}
